# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57deb30cbda73a4c48e2d90a79df727fdb6d924b73d597886829a2c689335f2c82f46eafe8a640866e1cd37e2a5d856c9e9cc43016738c70e8845263d424f0c0

test:
  secret_key_base: cdd35268bb9d328689ee9552dc29d44f2b4ad262c575d26f7d38576a10fcd1215989713bdfb999ce1bb41d89218ace2b997f47eb9dd1b9c9ff4c9d7e14162c96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
